export { default as SignIn } from './Auth/SignIn';
export { default as SignUp } from './Auth/SignUp';
export { default as SocialLogin } from './Auth/SocialLogin';
export { default as HomePage } from './Home/HomePage';
export { default as JobDetails } from './Jobs/JobDetails';
export { default as ApplyJob } from './Applications/ApplyJob';
export { default as MyApplications } from './Applications/MyApplications';
export { default as AddJob } from './Admin/AddJob';
export { default as MyPostedJobs } from './Post/MyPostedJobs';
